version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../../configs:/app/configs:ro
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: 