version: '3.8'

services:
  app:
    environment:
      - GIN_MODE=release
    restart: unless-stopped
    env_file:
      - ../../.env.prod

  redis:
    restart: unless-stopped
    expose:
      - "6379"  # Only expose Redis internally
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}" 